name: CI-CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-2"  # Ensure this matches your ECR and ECS regions

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry-type: private  # Optional: defaults to 'private'

      - name: Build Docker image
        run: |
          IMAGE_URI=${{ secrets.ECR_REPO_URI }}:latest
          docker build -t $IMAGE_URI .

      - name: Push Docker image to ECR
        run: |
          IMAGE_URI=${{ secrets.ECR_REPO_URI }}:latest
          docker push $IMAGE_URI



      # Uncomment and configure the following steps if you wish to deploy to ECS
      - name: Deploy to ECS
        uses: aws-actions/amazon-ecs-deploy@v1.12.0
        with:
          task-definition: "do-bot"
          service: "do-bot"
          cluster: "do-bot"
          wait-for-service-stability: true
          force-new-deployment: true
