name: CI-CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-2"  # Ensure this matches your ECR and ECS regions

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry-type: private  # Optional: defaults to 'private'

      - name: Build Docker image
        run: |
          IMAGE_URI=${{ secrets.ECR_REPO_URI }}:latest
          docker build -t $IMAGE_URI .

      - name: Push Docker image to ECR
        run: |
          IMAGE_URI=${{ secrets.ECR_REPO_URI }}:latest
          docker push $IMAGE_URI



      # Uncomment and configure the following steps if you wish to deploy to ECS
      - name: Replace Placeholders in Task Definition
        run: |
          # Export secrets as environment variables
          export ECS_SERVICE=${{ secrets.ECS_SERVICE }}
          export PORT=${{ secrets.PORT }}
          export GH_OWNER=${{ secrets.GH_OWNER }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          export AWS_DEFAULT_REGION=${{ secrets.AWS_DEFAULT_REGION }}
          export GH_REPO_NAME=${{ secrets.GH_REPO_NAME }}
          export GH_TOKEN=${{ secrets.GH_TOKEN }}
          export ECS_CLUSTER=${{ secrets.ECS_CLUSTER }}
          export SLACK_SIGNING_SECRET=${{ secrets.SLACK_SIGNING_SECRET }}
          export ADMIN_USER_IDS=${{ secrets.ADMIN_USER_IDS }}
          export GH_REPO=${{ secrets.GH_REPO }}
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          export ECR_REPO_URI=${{ secrets.ECR_REPO_URI }}
          export ECS_TASK_DEFINITION=${{ secrets.ECS_TASK_DEFINITION }}
          export OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
          export SLACK_APP_TOKEN=${{ secrets.SLACK_APP_TOKEN }}
          export SLACK_BOT_TOKEN=${{ secrets.SLACK_BOT_TOKEN }}

          envsubst < ecs-task-def.json > ecs-task-def-updated.json
      
      - name: Render Task Definition
        id: render-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ecs-task-def-updated.json
          container-name: "do-bot"
          image: ${{ secrets.ECR_REPO_URI }}:latest

      - name: Deploy to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.render-task-def.outputs.task-definition }}
          service: "do-bot"
          cluster: "do-bot"
          wait-for-service-stability: true
          force-new-deployment: true
