name: CI-CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-2"  # Ensure this matches your ECR and ECS regions

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry-type: private  # Optional: defaults to 'private'

      - name: Build Docker image
        run: |
          IMAGE_URI=${{ secrets.ECR_REPO_URI }}:latest
          docker build -t $IMAGE_URI .

      - name: Push Docker image to ECR
        run: |
          IMAGE_URI=${{ secrets.ECR_REPO_URI }}:latest
          docker push $IMAGE_URI



      # Uncomment and configure the following steps if you wish to deploy to ECS
      # Step 7: Replace Placeholders in Task Definition
      - name: Replace Placeholders in Task Definition
        run: |
          # Export secrets as environment variables
          export OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
          export ADMIN_USER_IDS=${{ secrets.ADMIN_USER_IDS }}
          export GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          export SLACK_BOT_TOKEN=${{ secrets.SLACK_BOT_TOKEN }}
          export SLACK_SIGNING_SECRET=${{ secrets.SLACK_SIGNING_SECRET }}
          export IMAGE=${{ secrets.AWS_ECR_REGISTRY }}/do-bot:latest

      # Replace placeholders in ecs-task-def.json and save as ecs-task-def-updated.json
          envsubst < ecs-task-def.json > ecs-task-def-updated.json
      
      # Step 8: Render Task Definition with Updated Image
      - name: Render Task Definition
        id: render-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
         with:
          task-definition: ecs-task-def-updated.json
          container-name: "do-bot"             # Name of the container in the task definition
          image: ${{ secrets.AWS_ECR_REGISTRY }}/do-bot:latest

      # Step 9: Deploy to ECS
      - name: Deploy to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.render-task-def.outputs.task-definition }}
          service: "do-bot"            # Replace with your ECS service name
          cluster: "do-bot"            # Replace with your ECS cluster name
          wait-for-service-stability: true
          force-new-deployment: true
