name: CI-CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-2"
      
      - name: Build Docker image
        run: |
          IMAGE_URI=${{ secrets.ECR_REPO_URI }}:latest
          docker build -t $IMAGE_URI .
      
      - name: Push Docker image to ECR
        run: |
          IMAGE_URI=${{ secrets.ECR_REPO_URI }}:latest
          docker push $IMAGE_URI

#      - name: Deploy to ECS
#        uses: aws-actions/amazon-ecs-deploy@v1
#        with:
#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          region: ${{ secrets.AWS_DEFAULT_REGION }}
#          task-definition: "<YOUR_ECS_TASK_DEFINITION_NAME>"
#          service: "<YOUR_ECS_SERVICE_NAME>"
#          cluster: "<YOUR_ECS_CLUSTER_NAME>"
#          wait-for-service-stability: true
#          force-new-deployment: true
