name: CI-CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_DEFAULT_REGION }} \
          | docker login --username AWS --password-stdin ${{ secrets.ECR_REPO_URI }}

      - name: Build Docker image
        run: |
          docker build -t do-bot:latest .

      - name: Tag Docker image
        run: |
          docker tag do-bot:latest ${{ secrets.ECR_REPO_URI }}:latest

      - name: Push Docker image to ECR
        run: |
          docker push ${{ secrets.ECR_REPO_URI }}:latest

#      - name: Deploy to ECS
#        run: |
#          aws ecs update-service \
#            --cluster YOUR_ECS_CLUSTER_NAME \
#            --service YOUR_ECS_SERVICE_NAME \
#            --force-new-deployment
